version: "3.9"

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile_dev
    expose:
      - 3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./client:/app
  server:
    env_file: .dev.env
    environment: 
      - NODE_ENV=dev
    build:
      context: server
      dockerfile: Dockerfile_dev
    expose:
      - 5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./server:/app
  nginx:
    image: nginx:1
    restart: "no"
    ports:
      - 3000:80
    depends_on:
      - client
      - server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/dev:/etc/nginx/conf.d
      - ./client/dist:/usr/share/nginx/html
