version: "3.9"

services:
  nginx:
    image: nginx
    restart: "no"
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/prod:/etc/nginx/conf.d  
      - ./client/dist:/usr/share/nginx/html

